### PR TITLE
fixes #220 (for add operations, append values to end incase of array attribute)

### LINKED ISSUE #220: 'add' on array attribute performs 'replace' when 'path' is absent
**Describe the bug**

Let's look at the following 4 code snippets and their corresponding outputs

### Case 1

**Code**

```js
const scimResource = {
    displayName: "ramayan",
    members: [
        { name: "ram" },
        { name: "laxman" }
    ]
}

const patches = {
    Operations: [
        {
            op: "add",
            path: "members",
            value: { name: "hanuman" }
        },
    ]
}

const patchedResource = scimPatch(scimResource, patches.Operations, { mutateDocument: false });
console.log(patchedResource);
```

**Output**
```js
{
  displayName: 'ramayan',
  members: [ { name: 'ram' }, { name: 'laxman' }, { name: 'hanuman' } ]
}
```

### Case 2

**Code**
```js
const scimResource = {
    displayName: "ramayan",
    members: [
        { name: "ram" },
        { name: "laxman" }
    ]
}

const patches = {
    Operations: [
        {
            op: "add",
            path: "members",
            value: [{ name: "hanuman" }]
        },
    ]
}

const patchedResource = scimPatch(scimResource, patches.Operations, { mutateDocument: false });
console.log(patchedResource);
```

**Output**
```js
{
  displayName: 'ramayan',
  members: [ { name: 'ram' }, { name: 'laxman' }, { name: 'hanuman' } ]
}
```

### Case 3

**Code**
```js
const scimResource = {
    displayName: "ramayan",
    members: [
        { name: "ram" },
        { name: "laxman" }
    ]
}

const patches = {
    Operations: [
        {
            op: "add",
            value: {
                members: { name: "hanuman" }
            }
        },
    ]
}

const patchedResource = scimPatch(scimResource, patches.Operations, { mutateDocument: false });
console.log(patchedResource);
```

**Output**
```js
{ displayName: 'ramayan', members: { name: 'hanuman' } }
```

### Case 4

**Code**
```js
const scimResource = {
    displayName: "ramayan",
    members: [
        { name: "ram" },
        { name: "laxman" }
    ]
}

const patches = {
    Operations: [
        {
            op: "add",
            value: {
                members: [{ name: "hanuman" }]
            }
        },
    ]
}

const patchedResource = scimPatch(scimResource, patches.Operations, { mutateDocument: false });
console.log(patchedResource);
```

**Output**
```js
{ displayName: 'ramayan', members: [ { name: 'hanuman' } ] }
```

Case 1 & 2 give the correct output, whereas case 3 & 4 produce the wrong output.
For case 3 & 4, if the operation was "replace", then that output would have been correct.

I've figured out a fix, will be creating a PR soon

### PR DESCRIPTION
**Pull request by asutosh97**
# Description

Fixes #220 

# Changes include
- [x] Bugfix (non-breaking change that solves an issue)

# Closes issue(s)
Resolve #220 

# Checklist
- [x] I have tested this code
- [x] I have added unit test to cover this code
- [x] I have updated the Readme
- [x] I have followed the [contributing guide](CONTRIBUTING.md)

### CODE REVIEW

File: src/scimPatch.ts [hunk 1]
```diff
@@ -401,6 +402,21 @@ function assign(obj:any, keyPath:Array<string>, value:any) {
...
         obj = obj[key];
     }
+
+    // If the attribute is an array and the operation is "add",
+    // then the value should be added to the array
+    const attribute = obj[keyPath[lastKeyIndex]];
+    if (op.toLowerCase() === "add" && Array.isArray(attribute)) {
+        // If the value is also an array, append all values of the array to the attribute
+        if (Array.isArray(value)) {
+            value.forEach((val) => attribute.push(val));
```
Comment (thomaspoignant) [inline src/scimPatch.ts:412]: I would prefer to affect the value to `obj` it make it more readable.

I propose to use something like that:
```suggestion
            obj[keyPath[lastKeyIndex]] = [...attribute, ...value];
```

File: src/scimPatch.ts [hunk 2]
```diff
@@ -401,6 +402,21 @@ function assign(obj:any, keyPath:Array<string>, value:any) {
...
+            return;
+        }
+
+        // If value is not an array, simply append it as a whole to end of attribute
+        attribute.push(value);
```
Comment (thomaspoignant) [inline src/scimPatch.ts:417]: Same as the other, I'll prefer to affect directly into the array.
```suggestion
        obj[keyPath[lastKeyIndex]] = [...attribute, value];
```

**Review by thomaspoignant — CHANGES_REQUESTED** [review]
@asutosh97 Thanks a lot for this PR, all your fixes help a lot 🚀.
I have some minor changes I would do, let me think what you think about them?

File: src/scimPatch.ts (hunk 1 above)
Comment (asutosh97) [reply src/scimPatch.ts:412]: @thomaspoignant 
Right, agree with the readability point, good observation.
Obvious code is always better than smart code which needs to be figured out, which in this case was: since `attribute` is an array, `obj` & `attribute` share the same reference rather than copies. Though correct, this needs a little bit of mental work to figure out.

So yeah, we can go ahead with your suggestion, that's better 👍

**Review by thomaspoignant — APPROVED** [review]
