### PR TITLE
Path with a complex filter match only the first occurrence

### LINKED ISSUE #503: Path with a complex filter match only the first occurrence
**Describe the bug**
When using a selection filter on multi-valued complex attribute only the first occurrence is considered.

**To Reproduce**
```
const scimUser: ScimUser = {
    schemas: ['urn:ietf:params:scim:schemas:core:2.0:User'],
    userName: 'user1@test.com',
    name: { familyName: 'user1', givenName: 'user2' },
    active: true,
    emails: [
        {value: 'user1@test.com', primary: true},
        {value: 'user2@test.com', primary: true},
        {value: 'user3@test.com', primary: true},
        {value: 'user1@gmail.com', primary: false},
        {value: 'user2@gmail.com', primary: false},
        {value: 'user3@gmail.com', primary: false},
        {value: 'user4@gmail.com', primary: false},
        {value: 'user5@gmail.com', primary: false},
        {value: 'user6@gmail.com', primary: false},
        {value: 'user7@gmail.com', primary: false},
        {value: 'user8@gmail.com', primary: false},
    ],
    meta: { resourceType: 'User', created: new Date(), lastModified: new Date() }
};

const patches: ScimPatchOperation[] = [
    { op: 'replace', path: 'emails[value co "gmail"].value', value: 'edited-user1@yahoo.com'  }, // Match only first
    { op: 'replace', path: 'emails[value co "gmail"]', value: { value:'edited-user2@yahoo.com' } }, // Match only first
    { op: 'add', path: 'emails[value co "gmail"]', value: { value:'edited-user3@yahoo.com' } }, // Match only first
    { op: 'add', path: 'emails[value co "gmail"].value', value:'edited-user4@yahoo.com'}, // Match only first (*)
    { op: 'remove', path: 'emails[value co "gmail"].value'}, // Match only first
    // { op: 'remove', path: 'emails[value co "gmail"]'}, // This match all the sele
];

const patchedUser = scimPatch(scimUser, patches);
console.log(patchedUser)
```
`ScimUser` is  defined as in the README

**Expected behavior**
Is expected that these operation apply to all attributes that satisfy the filter.

I'm not sure that this is the correct way to interpret the RFC. 
The only one explained clearly is the one marked by the `*` in the last point of page 43 (of RFC 7644)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 LTS (WSL)
 - Node: 18.14.0

### PR DESCRIPTION
**Pull request by leonardo-speranzon**
# Description

To solve this bug i changed slightly the logic of `navigate`, `applyRemoveOperation()` and `applyRemoveOperation()` to work with multiple paths (arrays of paths) instead of a single one.
I've added some test for checking the cases discussed in the issue.

**In the new code there is FIXME describing a possible unwanted error, but it should be only caused by some schemas out of the SCIM standard (with depth greater than 1). If it is ok i can remove the comment otherwise i can try to fix it**

# Changes include
- [x] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking changes (change that is not backward-comptible and/or changes current functionality)

# Closes issue(s)

Resolve #503 

# Checklist
- [x] I have tested this code
- [x] I have added unit test to cover this code
- [ ] I have updated the Readme
- [ ] I have followed the [contributing guide](CONTRIBUTING.md)

### CODE REVIEW

File: src/scimPatch.ts [hunk 1]
```diff
@@ -261,29 +266,39 @@ function applyAddOrReplaceOperation<T extends ScimResource>(scimResource: T, pat
         }
         throw e;
     }
-
+    // console.log(resources_scoped);
+    // console.log({op:patch.op,len:resources_scoped.length, lastSubPath});
```
Comment (thomaspoignant) [inline src/scimPatch.ts:270]: Can you remove those commented `console.log` ?

**Review by thomaspoignant — DISMISSED** [review]
Thanks a lot for this contribution this is awesome and it fixes an important loop hole.

I've just put some NIT comments about some commented logs if you can have a look.
As soon as you've fixed it I will create a new version.
